### ISSUE TITLE
mMain怎么来的

### ISSUE THREAD

**Issue by remembersun** [bin2415/llvm_CGPass#1]
你好，我看了你关于函数调用图的代码，其中有一些问题一直不能解决，想问一下你：
1、G = new CallGraph(main);
这一行代是在CGpass.cpp文件中，我不知道这行代码能实现什么功能？
2、CallGraph（Function * mainFunc）：mMain（mainFunc）{}
这行代码是在CGPass.h文件中，我想问一下这个mMain是在哪里定义的。
3、您能讲解一下，如果想要把这个Pass单独拿出来形成一个控制台程序，应该如何修改呢

感谢您

**Comment by bin2415** [comment]
For 1: CallGraph类在CGPass.h里面有定义，主要是保存call graph的信息

For 2: mMain是一个Function* 类型的，在CGPass.h有定义

For 3: 这个方法提取的Call Graph比较简单，没有考虑函数指针的情况，所以建议你可以考虑添加指针别名的算法等。另外opt也有提供得到Call Graph的方法，https://llvm.org/docs/Passes.html#dot-callgraph-print-call-graph-to-dot-file

希望能帮助到你
